In [1]:
import matplotlib as plt
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data_utf_8/plus_y_data_CLAIM_DATA_utf_8_extract', index_col=0)

In [3]:
df.columns

Index(['SIU_CUST_YN', 'CUST_ID', 'POLY_NO', 'ACCI_OCCP_GRP1', 'ACCI_OCCP_GRP2',
       'CHANG_FP_YN', 'CNTT_RECP_SQNO', 'RECP_DATE', 'ORIG_RESN_DATE',
       'RESN_DATE', 'CRNT_PROG_DVSN', 'ACCI_DVSN', 'CAUS_CODE',
       'CAUS_CODE_DTAL', 'DSAS_NAME', 'DMND_RESN_CODE', 'DMND_RSCD_SQNO',
       'HOSP_OTPA_STDT', 'HOSP_OTPA_ENDT', 'RESL_CD1', 'RESL_NM1',
       'VLID_HOSP_OTDA', 'HOUSE_HOSP_DIST', 'HOSP_CODE', 'ACCI_HOSP_ADDR',
       'HOSP_SPEC_DVSN', 'CHME_LICE_NO', 'PAYM_DATE', 'DMND_AMT', 'PAYM_AMT',
       'PMMI_DLNG_YN', 'SELF_CHAM', 'NON_PAY', 'TAMT_SFCA', 'PATT_CHRG_TOTA',
       'DSCT_AMT', 'COUNT_TRMT_ITEM', 'DCAF_CMPS_XCPA', 'NON_PAY_RATIO',
       'HEED_HOSP_YN'],
      dtype='object')

In [4]:
# 결과값 수치화하는 변수입니다.
df["SIU_CUST_YN"] = df["SIU_CUST_YN"].map(lambda x : 1 if x == 'Y' else 0)    #N은 0,Y는 1

In [5]:
y_data = df["SIU_CUST_YN"]

In [6]:
sion = df["SIU_CUST_YN"].groupby(df["ACCI_OCCP_GRP1"])
sion.mean()

ACCI_OCCP_GRP1
1.주부      0.270792
2.자영업     0.320294
3.사무직     0.212187
4.전문직     0.144129
5.서비스     0.250013
6.제조업     0.149673
7.1차산업    0.135987
8.기타      0.177953
Name: SIU_CUST_YN, dtype: float64

In [7]:
df["ACCI_OCCP_GRP1"] = df["ACCI_OCCP_GRP1"].map(lambda x : 4 if x == '2.자영업' else x)   

In [8]:
df["ACCI_OCCP_GRP1"] = df["ACCI_OCCP_GRP1"].map(lambda x : 3 if x == '1.주부' or x == '5.서비스' else x)    

In [9]:
df["ACCI_OCCP_GRP1"] = df["ACCI_OCCP_GRP1"].map(lambda x : 2 if x == '3.사무직' or x == '8.기타' else x)   

In [10]:
df["ACCI_OCCP_GRP1"] = df["ACCI_OCCP_GRP1"].map(lambda x : 1 if x == '4.전문직' or x == '6.제조업' or x == '7.1차산업' else x)    

In [11]:
df["ACCI_OCCP_GRP1"].fillna((df["ACCI_OCCP_GRP1"].mean()), inplace=True)

In [12]:
x_data_1 = df["ACCI_OCCP_GRP1"]

In [13]:
np.corrcoef(x_data_1,y_data)

array([[ 1.        ,  0.12744665],
       [ 0.12744665,  1.        ]])

In [14]:
sion_version_2 = df["SIU_CUST_YN"].groupby(df["ACCI_OCCP_GRP2"])
sion_version_2.mean()

ACCI_OCCP_GRP2
1차산업 종사자    0.141960
2차산업 종사자    0.160143
3차산업 종사자    0.275085
고소득 전문직     0.000000
고소득의료직      0.074627
고위 공무원      0.088949
공무원         0.160391
교사          0.076923
교육관련직       0.188889
기업/단체 임원    0.172316
기타          0.058252
단순 노무직      0.071594
단순 사무직      0.285470
대학교수/강사     0.351064
법무직 종사자     0.000000
사무직         0.214146
예체능계 종사자    0.281669
운전직         0.173880
의료직 종사자     0.068638
자영업         0.319606
전문직         0.130687
종교인/역술인     0.240909
주부          0.269979
학생          0.186105
학자/연구직      0.092105
Name: SIU_CUST_YN, dtype: float64

In [15]:
df["ACCI_OCCP_GRP2"] = df["ACCI_OCCP_GRP2"].map(lambda x : 10 if x == '대학교수/강사' or x == '자영업' else 1)   

In [16]:
df["ACCI_OCCP_GRP2"] = df["ACCI_OCCP_GRP2"].map(lambda x : 5 if x == '단순 사무직'or x == '3차산업 종사자' or x == '사무직' or x == '종교인/역술인' or x == '주부' else x)   

In [17]:
df["ACCI_OCCP_GRP2"] = df["ACCI_OCCP_GRP2"].map(lambda x : 2 if x == '교육관련직' or x == '기업/단체 임원' or x == '1차산업 종사자' or x == '2차산업 종사자' or x == '전문직' or x == '학생' else x)   

In [18]:
df["ACCI_OCCP_GRP2"].fillna((df["ACCI_OCCP_GRP2"].mean()), inplace=True)

In [19]:
x_data_2 = df["ACCI_OCCP_GRP2"]

In [20]:
np.corrcoef(x_data_2,y_data)

array([[ 1.        ,  0.07675078],
       [ 0.07675078,  1.        ]])

In [21]:
sion_version_3 = df["SIU_CUST_YN"].groupby(df["CNTT_RECP_SQNO"])
sion_version_3.mean()

CNTT_RECP_SQNO
2006010600001    0
2006010600002    0
2006010600003    0
2006010600004    0
2006010900001    0
2006010900002    0
2006010900003    0
2006011000001    0
2006011000002    1
2006011000003    1
2006011000004    0
2006011000005    0
2006011000006    1
2006011000007    1
2006011000008    0
2006011100001    0
2006011100002    0
2006011100003    0
2006011100006    0
2006011200001    0
2006011200002    0
2006011200003    0
2006011200004    0
2006011200005    0
2006011200006    0
2006011300001    0
2006011300003    0
2006011300004    0
2006011300005    1
2006011300006    0
                ..
2215051200001    0
2215051300001    0
2215051900001    0
2215051900002    0
2215052000001    0
2215052600001    0
2215061000001    0
2215061500001    0
2215061800001    0
2215061800002    0
2215061900001    0
2215061900002    0
2215062500001    0
2215062900001    0
2215063000001    0
2215070200001    0
2215070300001    0
2215070900001    0
2215071300001    0
2215072100001    1
2215072100002   

In [22]:
sion_version_4 = df["SIU_CUST_YN"].groupby(df["RECP_DATE"])
sion_version_4.mean()

RECP_DATE
20060106    0.000000
20060109    0.000000
20060110    0.500000
20060111    0.000000
20060112    0.000000
20060113    0.166667
20060116    0.666667
20060117    0.111111
20060118    0.222222
20060119    0.666667
20060120    0.000000
20060123    0.500000
20060124    0.100000
20060125    0.750000
20060126    0.500000
20060127    0.363636
20060131    0.125000
20060201    0.714286
20060202    0.750000
20060203    0.500000
20060206    0.333333
20060207    0.500000
20060208    0.000000
20060209    0.444444
20060210    0.000000
20060213    0.153846
20060214    0.166667
20060215    0.125000
20060216    0.200000
20060217    0.250000
              ...   
20160520    0.107143
20160523    0.092593
20160524    0.047619
20160525    0.120000
20160526    0.020000
20160527    0.107692
20160530    0.065574
20160531    0.185185
20160601    0.017241
20160602    0.049180
20160603    0.115385
20160607    0.211538
20160608    0.080645
20160609    0.087912
20160610    0.046512
20160613    0.064516
201

In [23]:
sion_version_5 = df["SIU_CUST_YN"].groupby(df["ORIG_RESN_DATE"])
sion_version_5.mean()

ORIG_RESN_DATE
19990428    0.000000
19990622    1.000000
19991103    1.000000
19991112    1.000000
20000120    0.000000
20000512    0.000000
20000524    1.000000
20001012    0.000000
20001022    1.000000
20001030    0.000000
20010203    0.000000
20010625    0.000000
20010629    1.000000
20010726    0.000000
20010731    0.000000
20010821    0.000000
20011022    0.000000
20011130    0.000000
20020105    0.000000
20020212    0.750000
20020215    0.000000
20020314    0.000000
20020415    0.000000
20020604    0.000000
20020623    0.000000
20020702    0.000000
20020703    0.000000
20020716    1.000000
20020723    1.000000
20020925    0.000000
              ...   
20160526    0.066667
20160527    0.000000
20160528    0.000000
20160529    0.000000
20160530    0.363636
20160531    0.000000
20160601    0.130435
20160602    0.076923
20160603    0.000000
20160604    0.100000
20160605    0.000000
20160606    0.000000
20160607    0.050000
20160608    0.000000
20160609    0.000000
20160610    0.00000

In [24]:
sion_version_6 = df["SIU_CUST_YN"].groupby(df["RESN_DATE"])
sion_version_6.mean()

RESN_DATE
20060101    0.166667
20060102    0.500000
20060103    0.636364
20060104    0.181818
20060105    0.142857
20060106    0.333333
20060107    0.166667
20060108    0.000000
20060109    0.240000
20060110    0.250000
20060111    0.625000
20060112    0.333333
20060113    0.133333
20060114    0.666667
20060115    0.333333
20060116    0.066667
20060117    0.357143
20060118    0.000000
20060119    0.363636
20060120    0.090909
20060121    0.666667
20060122    0.000000
20060123    0.571429
20060124    0.285714
20060125    0.285714
20060126    0.142857
20060127    0.200000
20060128    0.000000
20060129    0.000000
20060130    0.000000
              ...   
20160528    0.000000
20160529    0.000000
20160530    0.117647
20160531    0.176471
20160601    0.107143
20160602    0.000000
20160603    0.043478
20160604    0.083333
20160605    0.000000
20160606    0.000000
20160607    0.047619
20160608    0.000000
20160609    0.047619
20160610    0.000000
20160611    0.076923
20160612    0.000000
201

In [25]:
sion_version_7 = df["SIU_CUST_YN"].groupby(df["CRNT_PROG_DVSN"])
sion_version_7.mean()

CRNT_PROG_DVSN
11    0.178949
21    0.000000
22    0.000000
23    0.218517
33    0.373716
Name: SIU_CUST_YN, dtype: float64

In [26]:
df["CRNT_PROG_DVSN"] = df["CRNT_PROG_DVSN"].map(lambda x : 10 if x == 33 else x)   

In [27]:
df["CRNT_PROG_DVSN"] = df["CRNT_PROG_DVSN"].map(lambda x : 6 if x == 23 else x)   

In [28]:
df["CRNT_PROG_DVSN"] = df["CRNT_PROG_DVSN"].map(lambda x : 3 if x == 11 else x)   

In [29]:
df["CRNT_PROG_DVSN"] = df["CRNT_PROG_DVSN"].map(lambda x : 1 if x != 10 and x != 6 and x != 3 else x)   

In [30]:
df["CRNT_PROG_DVSN"].fillna((df["CRNT_PROG_DVSN"].mean()), inplace=True)

In [31]:
x_data_3 = df["CRNT_PROG_DVSN"]

In [32]:
np.corrcoef(x_data_3,y_data)

array([[ 1.        ,  0.10382553],
       [ 0.10382553,  1.        ]])

In [33]:
sion_version_8 = df["SIU_CUST_YN"].groupby(df["CAUS_CODE"])
sion_version_8.mean()

CAUS_CODE
A02    0.250000
A04    0.220779
A05    0.517241
A06    0.000000
A07    0.000000
A08    0.377049
A09    0.303380
A15    0.085106
A16    0.018519
A17    0.000000
A18    0.031250
A19    0.000000
A31    0.000000
A38    0.000000
A41    0.166667
A42    0.000000
A49    0.142857
A54    0.000000
A56    0.000000
A59    0.000000
A60    0.000000
A63    0.000000
A75    0.000000
A86    0.200000
A87    0.027778
A91    0.000000
B00    0.133333
B01    0.461538
B02    0.214634
B07    0.000000
         ...   
X30    0.500000
X44    0.000000
X47    1.000000
X48    0.000000
X49    0.000000
X58    0.000000
X67    0.000000
X70    0.200000
X71    0.750000
X76    0.000000
X78    0.000000
X80    0.000000
X83    0.000000
X91    0.000000
X92    0.000000
X95    0.000000
X99    0.000000
Y00    0.000000
Y04    0.000000
Y14    0.000000
Y21    0.000000
Y27    1.000000
Y28    0.000000
Y29    0.000000
Y30    0.190476
Y45    0.000000
Y83    0.400000
Z01    0.000000
Z03    0.000000
Z11    0.000000
Name: SIU_CUST

In [34]:
sion_version_9 = df["SIU_CUST_YN"].groupby(df["CAUS_CODE_DTAL"])
sion_version_9.mean()

CAUS_CODE_DTAL
#      0.216164
0      0.239564
00     0.118734
01     0.236434
02     0.228188
021    1.000000
03     0.000000
04     0.576923
05     0.000000
06     0.183150
07     0.219512
08     0.000000
09     0.066176
1      0.233532
10     0.134731
100    0.058824
108    0.166667
11     0.114504
110    0.303030
118    0.454545
12     0.357143
13     0.285714
138    0.000000
14     0.111111
15     0.523810
150    1.000000
158    0.666667
16     0.404762
17     0.239130
173    0.000000
         ...   
79     0.000000
8      0.246831
80     0.184466
81     0.107843
82     0.126050
83     0.000000
84     0.090909
85     0.192308
86     0.262295
87     0.680000
88     0.257812
889    0.000000
89     0.090909
9      0.228067
90     0.057785
900    1.000000
91     0.286920
910    0.000000
92     0.105691
93     0.095238
930    0.000000
94     0.239130
95     0.187500
96     0.371622
969    0.000000
97     0.663366
970    0.000000
98     0.153846
980    1.000000
99     0.114833
Name: SIU

In [35]:
sion_version_10 = df["SIU_CUST_YN"].groupby(df["DSAS_NAME"])
sion_version_10.mean()

DSAS_NAME
# 11번치아치수침범이있는치관파절        0.0
# 17 치관파절                 0.0
#11 치관파절                  0.0
#11 치수침범없는 치아파절           0.0
#11 치수침범이있는치관파절           0.0
#11 치아파절                  0.0
#11.21 절단면 치아파절           0.0
#11.21번 치관치근파절            0.0
#11|#21 치관파절              0.0
#11|#21 치아파절              0.0
#11|12 법랑질만의파절            1.0
#11|12 치관파절               0.0
#11|12 치아파절               0.0
#11|12치관파절                0.0
#11|21 치관-치근파절            0.0
#11|21 치수침범이없는 치관파절       0.0
#11|21 치수침범이없는치관파절        0.0
#11|21 치조골이식술             0.0
#11|21-개방성치아의파절           0.0
#11|21-치관파절               1.0
#11|21|13|14 치조골 이식술      0.0
#11|21|22 치아파절            0.0
#11|21치관파절법랑질             0.0
#11법랑질만의 파절               0.0
#11법랑질파절                  0.0
#11치수침범이없는치관파절            0.0
#12 레진                    0.0
#12 치아파절                  0.0
#12 치조골이식                 0.0
#12 치조골이식술                0.0
                         ... 
흉통                        0.0
흉통(갈비뼈의염증)                0.0


In [36]:
sion_version_11 = df["SIU_CUST_YN"].groupby(df["DMND_RESN_CODE"])
sion_version_11.mean()

DMND_RESN_CODE
1    0.065574
2    0.332205
3    0.080641
4    0.333729
5    0.129745
6    0.098380
7    0.025974
9    0.000000
Name: SIU_CUST_YN, dtype: float64

In [37]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 100 if x == 2 or x == 4 else x)   

In [38]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 40 if x == 5 else x)   

In [39]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 10 if x == 1 or x == 3 or x == 6 else x)   

In [40]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 5 if x == 7 else x)   

In [41]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 1 if x == 9 else x)   

In [42]:
df["DMND_RESN_CODE"].fillna((df["DMND_RESN_CODE"].mean()), inplace=True)

In [43]:
x_data_4 = df["DMND_RESN_CODE"]

In [44]:
np.corrcoef(x_data_4,y_data)

array([[ 1.        ,  0.27636991],
       [ 0.27636991,  1.        ]])

In [45]:
sion_version_12 = df["SIU_CUST_YN"].groupby(df["HOSP_OTPA_STDT"])
sion_version_12.mean()

HOSP_OTPA_STDT
20060101.0    0.333333
20060102.0    0.625000
20060103.0    0.600000
20060104.0    0.333333
20060105.0    0.200000
20060106.0    0.500000
20060107.0    0.181818
20060108.0    0.000000
20060109.0    0.277778
20060110.0    0.428571
20060111.0    0.666667
20060112.0    0.500000
20060113.0    0.100000
20060114.0    0.666667
20060115.0    0.333333
20060116.0    0.142857
20060117.0    0.555556
20060118.0    0.000000
20060119.0    0.400000
20060120.0    0.000000
20060121.0    0.666667
20060122.0    0.000000
20060123.0    0.600000
20060124.0    0.200000
20060125.0    0.400000
20060126.0    0.000000
20060127.0    0.250000
20060128.0    0.000000
20060129.0    0.000000
20060130.0    0.000000
                ...   
20160526.0    0.000000
20160527.0    0.045455
20160528.0    0.000000
20160529.0    0.000000
20160530.0    0.120000
20160531.0    0.153846
20160601.0    0.083333
20160602.0    0.000000
20160603.0    0.050000
20160604.0    0.100000
20160605.0    0.000000
20160606.0    0.000

In [46]:
sion_version_13 = df["SIU_CUST_YN"].groupby(df["HOSP_OTPA_ENDT"])
sion_version_13.mean()

HOSP_OTPA_ENDT
20060105.0    0.800000
20060106.0    0.250000
20060107.0    0.000000
20060109.0    0.000000
20060110.0    0.000000
20060111.0    0.000000
20060112.0    0.400000
20060113.0    0.250000
20060114.0    0.285714
20060116.0    0.222222
20060117.0    0.000000
20060118.0    0.333333
20060119.0    0.500000
20060120.0    0.000000
20060121.0    0.333333
20060122.0    1.000000
20060123.0    0.181818
20060124.0    0.000000
20060125.0    1.000000
20060126.0    0.500000
20060127.0    0.400000
20060128.0    1.000000
20060129.0    0.000000
20060131.0    0.750000
20060201.0    0.428571
20060202.0    0.500000
20060203.0    0.000000
20060204.0    0.666667
20060205.0    0.000000
20060206.0    0.500000
                ...   
20160531.0    0.173913
20160601.0    0.000000
20160602.0    0.125000
20160603.0    0.000000
20160604.0    0.043478
20160605.0    0.000000
20160606.0    0.285714
20160607.0    0.173913
20160608.0    0.115385
20160609.0    0.066667
20160610.0    0.000000
20160611.0    0.100

In [47]:
sion_version_14 = df["SIU_CUST_YN"].groupby(df["RESL_CD1"])
sion_version_14.mean()

RESL_CD1
A02    0.250000
A04    0.220779
A05    0.517241
A06    0.000000
A07    0.000000
A08    0.377049
A09    0.303380
A15    0.085106
A16    0.018519
A17    0.000000
A18    0.031250
A19    0.000000
A31    0.000000
A38    0.000000
A41    0.166667
A42    0.000000
A49    0.142857
A54    0.000000
A56    0.000000
A59    0.000000
A60    0.000000
A63    0.000000
A75    0.000000
A86    0.200000
A87    0.027778
A91    0.000000
B00    0.133333
B01    0.461538
B02    0.214634
B07    0.000000
         ...   
T58    1.000000
T60    0.000000
T61    0.000000
T62    0.000000
T63    0.000000
T65    0.000000
T67    0.000000
T69    0.000000
T71    0.000000
T75    0.000000
T78    0.083333
T79    0.000000
T81    0.000000
T84    0.000000
T88    0.000000
T90    0.000000
T93    0.000000
T96    0.000000
T98    0.000000
V43    0.000000
X67    0.000000
X70    0.200000
X71    0.750000
X76    0.000000
X78    0.000000
X80    0.000000
X83    0.000000
Z01    0.000000
Z03    0.000000
Z11    0.000000
Name: SIU_CUST_

In [48]:
sion_version_15 = df["SIU_CUST_YN"].groupby(df["RESL_NM1"])
sion_version_15.mean()

RESL_NM1
T/NK-세포 림프종의 기타 명시된 형태           0.000000
가려움                              0.000000
가로막(횡격막)헤르니아                     0.666667
가슴(흉곽) 얕은(표재성)손상                 0.391304
가슴(흉곽)부위에서의 신경 및 척수의 손상          0.000000
가슴(흉곽)의 관절 및 인대의 탈구|염좌 및 긴장      0.335404
가슴(흉곽)의 기타 및 상세불명의 손상            0.333333
가슴(흉곽)의 열린(개방성)상처                0.000000
가운데귀(중이) 및 꼭지돌기(유양돌기)의 기타장애      0.500000
가운데귀(중이)의 진주종                    0.150000
가진통                              0.000000
각막 흉터 및 혼탁                       0.000000
각막염                              0.071429
각막의 기타장애                         0.000000
간및간내 담관의 악성신생물(암)                0.045852
간의 기타질환(지방간)                     0.522727
간의 섬유증 및 경화증                     0.508772
간질                               0.073171
간질 지속상태                          0.000000
감염성 단핵구증                         1.000000
감염성 및 기생충성질환에 대한 특수선별검사          0.000000
감염성 및 상세불명 기원의 기타위장염 및 결장염       0.303380
갑상선독증[갑상선기능항진증]                  0.092308
갑상선염                     

In [49]:
sion_version_16 = df["SIU_CUST_YN"].groupby(df["ACCI_HOSP_ADDR"])
sion_version_16.mean()

ACCI_HOSP_ADDR
강원    0.301153
경기    0.152801
경남    0.211361
경북    0.084682
광주    0.378514
대구    0.170135
대전    0.203577
부산    0.289071
서울    0.173838
세종    0.024390
울산    0.087677
인천    0.260595
전남    0.263982
전북    0.377941
제주    0.025478
충남    0.114426
충북    0.067681
Name: SIU_CUST_YN, dtype: float64

In [66]:
sion_version_16 = df["SIU_CUST_YN"].groupby(df["VLID_HOSP_OTDA"])
sion_version_16.mean()

VLID_HOSP_OTDA
0      0.123752
1      0.057765
2      0.069263
3      0.082794
4      0.093307
5      0.111155
6      0.120605
7      0.150772
8      0.194220
9      0.211426
10     0.258523
11     0.266766
12     0.308575
13     0.395680
14     0.556329
15     0.515931
16     0.443024
17     0.465986
18     0.487681
19     0.453802
20     0.539906
21     0.600100
22     0.582451
23     0.493936
24     0.470073
25     0.524169
26     0.494774
27     0.479212
28     0.529851
29     0.523109
         ...   
163    0.000000
165    1.000000
166    0.000000
168    0.000000
169    1.000000
170    0.000000
171    0.000000
172    1.000000
173    0.000000
174    0.000000
175    0.000000
177    1.000000
182    0.000000
183    0.000000
186    1.000000
190    0.000000
195    0.000000
205    0.000000
208    0.000000
212    1.000000
216    1.000000
228    0.000000
235    0.000000
237    0.000000
267    0.000000
274    1.000000
307    0.000000
308    0.000000
373    0.000000
578    0.000000
Name: SIU

In [59]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 100 if x ==10 else x)   


In [60]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x : 60 if x ==6 or x ==6 else x)   


In [61]:
df["DMND_RESN_CODE"] = df["DMND_RESN_CODE"].map(lambda x :0 if x !=100 or x ==60 else x)   


In [62]:
df["DMND_RESN_CODE"].fillna((df["DMND_RESN_CODE"].mean()), inplace=True)


In [63]:
x_data_4 = df["DMND_RESN_CODE"]


In [64]:
np.corrcoef(x_data_4,y_data)


array([[ 1.       ,  0.1072323],
       [ 0.1072323,  1.       ]])

In [54]:
sion_version_17 = df["SIU_CUST_YN"].groupby(df["HOSP_SPEC_DVSN"])
sion_version_17.mean()

HOSP_SPEC_DVSN
10.0    0.118064
20.0    0.236214
25.0    0.504649
30.0    0.237446
40.0    0.062257
45.0    0.117574
60.0    0.148936
70.0    0.118644
80.0    0.623477
85.0    0.442308
90.0    0.109375
95.0    0.381582
Name: SIU_CUST_YN, dtype: float64

In [55]:
sion_version_18 = df["SIU_CUST_YN"].groupby(df["CHME_LICE_NO"])
sion_version_18.mean()

CHME_LICE_NO
6           0.000000
7           0.000000
8           1.000000
9           0.000000
10          0.000000
11          0.000000
12          0.000000
13          0.000000
14          0.000000
15          0.000000
16          0.000000
17          0.375000
18          0.000000
19          0.000000
20          0.000000
21          0.000000
23          0.000000
24          0.000000
25          0.000000
27          1.000000
28          0.000000
29          0.000000
30          0.000000
31          1.000000
32          0.000000
33          0.000000
34          0.000000
35          0.000000
36          0.000000
37          0.000000
              ...   
25674       0.000000
25675       0.000000
25676       0.000000
25677       0.000000
25679       0.000000
25680       0.000000
25681       0.000000
25682       0.000000
25683       0.000000
25684       1.000000
25685       0.000000
25686       0.000000
25688       1.000000
25689       1.000000
25690       1.000000
25692       0.000000


In [56]:
sion_version_19 = df["SIU_CUST_YN"].groupby(df["PAYM_DATE"])
sion_version_19.mean()

PAYM_DATE
20060106.0    0.000000
20060109.0    0.000000
20060110.0    0.666667
20060111.0    0.000000
20060112.0    0.000000
20060113.0    0.000000
20060116.0    0.000000
20060117.0    0.600000
20060118.0    0.285714
20060119.0    0.250000
20060120.0    0.200000
20060123.0    0.400000
20060124.0    0.100000
20060125.0    0.666667
20060126.0    0.666667
20060127.0    0.500000
20060131.0    0.000000
20060201.0    0.600000
20060202.0    0.500000
20060203.0    0.800000
20060206.0    0.000000
20060207.0    0.250000
20060208.0    0.000000
20060209.0    0.454545
20060210.0    0.000000
20060213.0    0.000000
20060214.0    0.000000
20060215.0    0.300000
20060216.0    0.000000
20060217.0    0.333333
                ...   
20160520.0    0.101449
20160523.0    0.068966
20160524.0    0.080460
20160525.0    0.034483
20160526.0    0.020408
20160527.0    0.076923
20160530.0    0.062500
20160531.0    0.236842
20160601.0    0.037037
20160602.0    0.095238
20160603.0    0.051948
20160607.0    0.177778
2

In [57]:
sion_version_20 = df["SIU_CUST_YN"].groupby(df["PMMI_DLNG_YN"])
sion_version_20.mean()

PMMI_DLNG_YN
N    0.256323
Y    0.052979
Name: SIU_CUST_YN, dtype: float64

In [ ]:
sion_version_20 = df["SIU_CUST_YN"].groupby(df["PMMI_DLNG_YN"])
sion_version_20.mean()