In [45]:
import matplotlib as plt
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv('../data_utf_8/plus_y_data_CLAIM_DATA_utf_8_extract', index_col=0)

In [47]:
df.columns

Index(['SIU_CUST_YN', 'CUST_ID', 'POLY_NO', 'ACCI_OCCP_GRP1', 'ACCI_OCCP_GRP2',
       'CHANG_FP_YN', 'CNTT_RECP_SQNO', 'RECP_DATE', 'ORIG_RESN_DATE',
       'RESN_DATE', 'CRNT_PROG_DVSN', 'ACCI_DVSN', 'CAUS_CODE',
       'CAUS_CODE_DTAL', 'DSAS_NAME', 'DMND_RESN_CODE', 'DMND_RSCD_SQNO',
       'HOSP_OTPA_STDT', 'HOSP_OTPA_ENDT', 'RESL_CD1', 'RESL_NM1',
       'VLID_HOSP_OTDA', 'HOUSE_HOSP_DIST', 'HOSP_CODE', 'ACCI_HOSP_ADDR',
       'HOSP_SPEC_DVSN', 'CHME_LICE_NO', 'PAYM_DATE', 'DMND_AMT', 'PAYM_AMT',
       'PMMI_DLNG_YN', 'SELF_CHAM', 'NON_PAY', 'TAMT_SFCA', 'PATT_CHRG_TOTA',
       'DSCT_AMT', 'COUNT_TRMT_ITEM', 'DCAF_CMPS_XCPA', 'NON_PAY_RATIO',
       'HEED_HOSP_YN'],
      dtype='object')

In [48]:
# 첫번째 선정 변수 숫자화 과정입니다.

df["CHANG_FP_YN"]=df["CHANG_FP_YN"].map(lambda x : 1 if x == 'Y' else 0)      #동일할시 1
df["HEED_HOSP_YN"]=df["HEED_HOSP_YN"].map(lambda x : 1 if x == 'Y' else 0)    #사기병원 1

In [ ]:
# 결과값 수치화하는 변수입니다.
df["SIU_CUST_YN"] = df["SIU_CUST_YN"].map(lambda x : 1 if x == 'Y' else 0)    #N은 0,Y는 1

In [49]:
x_data_1 = df["CHANG_FP_YN"]
x_data_2 = df["ACCI_DVSN"]
x_data_3 = df["DMND_AMT"]
x_data_4 = df["PAYM_AMT"]
x_data_5 = df["HEED_HOSP_YN"]

y_data = df["SIU_CUST_YN"]

In [50]:
np.corrcoef(x_data_1,y_data)

array([[ 1.        , -0.05291529],
       [-0.05291529,  1.        ]])

In [51]:
np.corrcoef(x_data_2,y_data)

array([[ 1.        ,  0.03309189],
       [ 0.03309189,  1.        ]])

In [52]:
np.corrcoef(x_data_3,y_data)

array([[ 1.        ,  0.00679535],
       [ 0.00679535,  1.        ]])

In [53]:
np.corrcoef(x_data_4,y_data)

array([[ 1.        ,  0.00710697],
       [ 0.00710697,  1.        ]])

In [54]:
np.corrcoef(x_data_5,y_data)

array([[ 1.        ,  0.02947688],
       [ 0.02947688,  1.        ]])

In [55]:
# 두번째 선정 변수 측정하는 과정입니다.
x_data_6 = df["POLY_NO"]
x_data_7 = df["DMND_RSCD_SQNO"]
x_data_8 = df["VLID_HOSP_OTDA"]
#NAN이 나오는 변수
x_data_9 = df["HOUSE_HOSP_DIST"]
x_data_10 = df["HOSP_CODE"]
x_data_11 = df["SELF_CHAM"]
x_data_12 = df["NON_PAY"]
x_data_13 = df["TAMT_SFCA"]
x_data_14 = df["PATT_CHRG_TOTA"]
x_data_15 = df["DSCT_AMT"]
x_data_16 = df["COUNT_TRMT_ITEM"]
####
x_data_17 = df["NON_PAY_RATIO"]

In [56]:
np.corrcoef(x_data_6,y_data)

array([[ 1.        , -0.08654647],
       [-0.08654647,  1.        ]])

In [57]:
np.corrcoef(x_data_7,y_data)

array([[ 1.        , -0.02945279],
       [-0.02945279,  1.        ]])

In [58]:
np.corrcoef(x_data_8,y_data)

array([[ 1.        ,  0.25447212],
       [ 0.25447212,  1.        ]])

In [59]:
np.corrcoef(x_data_9,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [60]:
np.corrcoef(x_data_10,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [61]:
np.corrcoef(x_data_11,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [62]:
np.corrcoef(x_data_12,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [63]:
np.corrcoef(x_data_13,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [64]:
np.corrcoef(x_data_14,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [65]:
np.corrcoef(x_data_15,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [66]:
np.corrcoef(x_data_16,y_data)

array([[ nan,  nan],
       [ nan,   1.]])

In [69]:
np.corrcoef(x_data_17,y_data)

array([[ 1.        , -0.14388346],
       [-0.14388346,  1.        ]])

In [70]:
#NAN을 평균값으로 넣어주는 코드입니다.
df["HOUSE_HOSP_DIST"].fillna((df["HOUSE_HOSP_DIST"].mean()), inplace=True)
df["HOSP_CODE"].fillna((df["HOSP_CODE"].mean()), inplace=True)
df["SELF_CHAM"].fillna((df["SELF_CHAM"].mean()), inplace=True)
df["NON_PAY"].fillna((df["NON_PAY"].mean()), inplace=True)
df["TAMT_SFCA"].fillna((df["TAMT_SFCA"].mean()), inplace=True)
df["PATT_CHRG_TOTA"].fillna((df["PATT_CHRG_TOTA"].mean()), inplace=True)
df["DSCT_AMT"].fillna((df["DSCT_AMT"].mean()), inplace=True)
df["COUNT_TRMT_ITEM"].fillna((df["COUNT_TRMT_ITEM"].mean()), inplace=True)

x_data_9 = df["HOUSE_HOSP_DIST"]
x_data_10 = df["HOSP_CODE"]
x_data_11 = df["SELF_CHAM"]
x_data_12 = df["NON_PAY"]
x_data_13 = df["TAMT_SFCA"]
x_data_14 = df["PATT_CHRG_TOTA"]
x_data_15 = df["DSCT_AMT"]
x_data_16 = df["COUNT_TRMT_ITEM"]

In [71]:
np.corrcoef(x_data_9,y_data)

array([[ 1.        , -0.00981404],
       [-0.00981404,  1.        ]])

In [72]:
np.corrcoef(x_data_10,y_data)

array([[ 1.        , -0.00154302],
       [-0.00154302,  1.        ]])

In [73]:
np.corrcoef(x_data_11,y_data)

array([[ 1.        ,  0.00855654],
       [ 0.00855654,  1.        ]])

In [74]:
np.corrcoef(x_data_12,y_data)

array([[ 1.        ,  0.01636496],
       [ 0.01636496,  1.        ]])

In [75]:
np.corrcoef(x_data_13,y_data)

array([[ 1.        ,  0.00148594],
       [ 0.00148594,  1.        ]])

In [76]:
np.corrcoef(x_data_14,y_data)

array([[ 1.       ,  0.0155116],
       [ 0.0155116,  1.       ]])

In [77]:
np.corrcoef(x_data_15,y_data)

array([[ 1.        ,  0.00224935],
       [ 0.00224935,  1.        ]])

In [78]:
np.corrcoef(x_data_16,y_data)

array([[ 1.        , -0.00129396],
       [-0.00129396,  1.        ]])