In [57]:
import matplotlib as plt
import pandas as pd
import numpy as np
from math import sqrt
from statistics import mean
from numpy import array
import numpy as np

In [58]:
df = pd.read_csv('../data_utf_8/BGCON_CUST_DATA_utf_8_extract.txt', index_col=0)

In [59]:
df['FP_CAREER'] = df['FP_CAREER'].map(lambda x: 0 if x == 'N' else 1)
df['SIU_CUST_YN'] = df['SIU_CUST_YN'].map(lambda x: 0 if x == 'N' else 1)
df['WEDD_YN'] = df['WEDD_YN'].map(lambda x: 0 if x == 'N' else 1)


df_DIVIDED_SET = df["DIVIDED_SET"] 
df_SEX = df["SEX"]
df_AGE = df["AGE"]
df_RESI_COST = df["RESI_COST"]
df_RESI_TYPE_CODE = df["RESI_TYPE_CODE"]
df_FP_CAREER = df["FP_CAREER"]
df_CUST_RGST = df["CUST_RGST"]
df_CTPR = df["CTPR"]
df_OCCP_GRP_1 = df["OCCP_GRP_1"]
df_OCCP_GRP_2 = df["OCCP_GRP_2"]
df_TOTALPREM = df["TOTALPREM"]
df_MINCRDT = df["MINCRDT"]
df_MAXCRDT = df["MAXCRDT"]
df_WEDD_YN = df["WEDD_YN"]
df_MATE_OCCP_GRP_1 = df["MATE_OCCP_GRP_1"]
df_MATE_OCCP_GRP_2 = df["MATE_OCCP_GRP_2"]
df_CHLD_CNT = df["CHLD_CNT"]
df_LTBN_CHLD_AGE = df["LTBN_CHLD_AGE"]
df_MAX_PAYM_YM = df["MAX_PAYM_YM"]
df_MAX_PRM = df["MAX_PRM"]
df_CUST_INCM = df["CUST_INCM"]
df_RCBASE_HSHD_INCM = df["RCBASE_HSHD_INCM"]
df_JPBASE_HSHD_INCM = df["JPBASE_HSHD_INCM"]


df_SIU_CUST_YN = df["SIU_CUST_YN"]


In [60]:
df['DIVIDED_SET'].fillna((df['DIVIDED_SET'].mean()), inplace=True)
df['SEX'].fillna((df['SEX'].mean()), inplace=True)
df['AGE'].fillna((df['AGE'].mean()), inplace=True)
df['RESI_COST'].fillna((df['RESI_COST'].mean()), inplace=True)
df['RESI_TYPE_CODE'].fillna((df['RESI_TYPE_CODE'].mean()), inplace=True)
df['FP_CAREER'].fillna((df['FP_CAREER'].mean()), inplace=True)
df['CUST_RGST'].fillna((df['CUST_RGST'].mean()), inplace=True)
df['TOTALPREM'].fillna((df['TOTALPREM'].mean()), inplace=True)
df['MINCRDT'].fillna((df['MINCRDT'].mean()), inplace=True)
df['MAXCRDT'].fillna((df['MAXCRDT'].mean()), inplace=True)
df['CHLD_CNT'].fillna((df['CHLD_CNT'].mean()), inplace=True)
df['LTBN_CHLD_AGE'].fillna((df['LTBN_CHLD_AGE'].mean()), inplace=True)
df['MAX_PAYM_YM'].fillna((df['MAX_PAYM_YM'].mean()), inplace=True)
df['MAX_PRM'].fillna((df['MAX_PRM'].mean()), inplace=True)
df['CUST_INCM'].fillna((df['CUST_INCM'].mean()), inplace=True)
df['RCBASE_HSHD_INCM'].fillna((df['RCBASE_HSHD_INCM'].mean()), inplace=True)
df['JPBASE_HSHD_INCM'].fillna((df['JPBASE_HSHD_INCM'].mean()), inplace=True)

In [61]:
#AGE

df['AGE'] = df['AGE'].map(lambda x:0 if x < 11 else x)
df['AGE'] = df['AGE'].map(lambda x:10 if x >10 and x<21 else x)
df['AGE'] = df['AGE'].map(lambda x:20 if x >20 and x<31 else x)
df['AGE'] = df['AGE'].map(lambda x:30 if x >30 and x<41 else x)
df['AGE'] = df['AGE'].map(lambda x:40 if x >40 and x<51 else x)
df['AGE'] = df['AGE'].map(lambda x:50 if x >50 and x<61 else x)
df['AGE'] = df['AGE'].map(lambda x:60 if x >60 and x<71 else x)
df['AGE'] = df['AGE'].map(lambda x:70 if x >70 and x<81 else x)
df['AGE'] = df['AGE'].map(lambda x:80 if x >80  else x)

grouped = df['SIU_CUST_YN'].groupby(df['AGE'])
grouped.mean()

df['AGE'] = df['AGE'].map(lambda x:100 if x == 50 else x) 
df['AGE'] = df['AGE'].map(lambda x:70 if x == 30 or x == 40 or x == 60else x) 
df['AGE'] = df['AGE'].map(lambda x:40 if x == 20 else x) 
df['AGE'] = df['AGE'].map(lambda x:0 if  x != 100 and x!=70 and x!=40  else x)

In [62]:
x_data = df_AGE
y_data = df['SIU_CUST_YN']

np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.08830201],
       [ 0.08830201,  1.        ]])

In [63]:
df['MAXCRDT']

CUST_ID
1        19.529516
2         6.000000
3        19.529516
4        99.000000
5         8.000000
6         6.000000
7        19.529516
8        19.529516
9         6.000000
12        8.000000
13        7.000000
15       19.529516
16        6.000000
17       19.529516
18        8.000000
19        6.000000
20        6.000000
21       19.529516
22       99.000000
23       19.529516
24        6.000000
25       99.000000
26       19.529516
27        6.000000
28       99.000000
29        8.000000
30        6.000000
31       19.529516
32        6.000000
33        6.000000
           ...    
11063     6.000000
8711      6.000000
2058     19.529516
1699     19.529516
15499     6.000000
6156     19.529516
14826    19.529516
12570    19.529516
21572    19.529516
18279    19.529516
2409     19.529516
14389    19.529516
12858    19.529516
10744    19.529516
19371    19.529516
19375    19.529516
3561     19.529516
19406    19.529516
5926      6.000000
721      19.529516
19376     6.000000
1983

In [64]:
#MAXCRDT
df['MAXCRDT']= df['MAXCRDT'].map(lambda x:80 if x<6 else x)


In [65]:
df['MAXCRDT']= df['MAXCRDT'].map(lambda x:50 if x<50 and x>6 else x)


In [67]:
df['MAXCRDT'] = df['MAXCRDT'].map(lambda x:0 if x!= 80 and x!=50  else x)

In [68]:
df['MAXCRDT']

CUST_ID
1        50.0
2         0.0
3        50.0
4         0.0
5        50.0
6         0.0
7        50.0
8        50.0
9         0.0
12       50.0
13       50.0
15       50.0
16        0.0
17       50.0
18       50.0
19        0.0
20        0.0
21       50.0
22        0.0
23       50.0
24        0.0
25        0.0
26       50.0
27        0.0
28        0.0
29       50.0
30        0.0
31       50.0
32        0.0
33        0.0
         ... 
11063     0.0
8711      0.0
2058     50.0
1699     50.0
15499     0.0
6156     50.0
14826    50.0
12570    50.0
21572    50.0
18279    50.0
2409     50.0
14389    50.0
12858    50.0
10744    50.0
19371    50.0
19375    50.0
3561     50.0
19406    50.0
5926      0.0
721      50.0
19376     0.0
19838     0.0
21597     0.0
20276     0.0
2087      0.0
875      50.0
21483    50.0
21940     0.0
20356    50.0
17118    50.0
Name: MAXCRDT, dtype: float64

In [72]:
x_data = df['MAXCRDT']
y_data = df['SIU_CUST_YN']

np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.08542978],
       [ 0.08542978,  1.        ]])

In [17]:
#CTPR
df['CTPR'] = df['CTPR'].astype("category")

grouped = df['SIU_CUST_YN'].groupby(df['CTPR'])
grouped.mean()

df['CTPR'] = df['CTPR'].map(lambda x:50 if x == '강원' or x == '광주' or x == '부산' or x == '인천' or x == '전북' else x) 
df['CTPR'] = df['CTPR'].map(lambda x:30 if x == '경기' or x=='경남' or x=='경북'  or x=='대구'or x=='대전' or x=='서울' or x=='전남' else x)
df['CTPR'] = df['CTPR'].map(lambda x:0 if  x != 30 and x!=50  else x)


In [16]:
x_data = df['CTPR']
y_data = df['SIU_CUST_YN']


np.corrcoef(x_data, y_data)

array([[ 1.        ,  0.11247773],
       [ 0.11247773,  1.        ]])